from typing import List, Dict, Any
from archaeologist.ingest.ast_parser import CodeChunk

class ArchaeologicalReportExporter:
    """Generates Markdown and HTML technical report documents summarizing codebase excavation analytics."""
    
    def generate_markdown_report(
        self,
        stats: Dict[str, Any],
        chunks: List[CodeChunk],
        health: Dict[str, Any],
        diagram_code: str = ""
    ) -> str:
        """Constructs a comprehensive Markdown report document."""
        repo_path = stats.get("repo_path", "Unknown Repository")
        commits_mined = stats.get("commits_mined", 0)
        chunks_indexed = stats.get("chunks_indexed", len(chunks))
        files_parsed = stats.get("files_parsed", 0)
        
        md_lines = [
            f"# 🏛️ Archaeological Codebase Report: `{repo_path}`\n",
            f"*Generated by The Codebase Archaeologist*\n",
            "---",
            "## 📊 Executive Summary\n",
            f"- **Repository Path**: `{repo_path}`",
            f"- **Historical Commits Mined**: `{commits_mined}`",
            f"- **AST Code Chunks Indexed**: `{chunks_indexed}`",
            f"- **Total Files Parsed**: `{files_parsed}`\n",
            "---",
            "## 🏥 Codebase Health & Technical Debt Audit\n",
            f"- **Health Index Score**: `{health.get('health_score', 100)}/100`",
            f"- **Risk Assessment**: `{health.get('risk_level', 'Low Risk')}`",
            f"- **Average Chunk Size**: `{health.get('avg_chunk_lines', 0)} lines`",
            f"- **Oversized Chunks (>80 lines)**: `{health.get('oversized_chunks', 0)}` ({health.get('oversized_ratio_percent', 0)}%)\n"
        ]
        
        # Git Churn Hotspots
        churn_hotspots = health.get("churn_hotspots", [])
        if churn_hotspots:
            md_lines.append("### ⏳ High Churn Hotspots")
            for item in churn_hotspots:
                md_lines.append(f"- `{item['file']}`: {item['commit_count']} recent commits")
            md_lines.append("")
            
        # Component Architecture Diagram
        if diagram_code:
            md_lines.extend([
                "---",
                "## 🏛️ Component Architecture Map\n",
                "```mermaid",
                diagram_code,
                "```\n"
            ])
            
        md_lines.append("---\n*End of Archaeological Technical Report*")
        return "\n".join(md_lines)

    def generate_html_report(
        self,
        stats: Dict[str, Any],
        chunks: List[CodeChunk],
        health: Dict[str, Any],
        diagram_code: str = ""
    ) -> str:
        """Constructs an HTML technical report document."""
        md_content = self.generate_markdown_report(stats, chunks, health, diagram_code)
        
        html_doc = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Archaeological Codebase Report</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #0f172a; color: #f8fafc; padding: 2rem; max-width: 900px; margin: auto; }}
        h1, h2, h3 {{ color: #38bdf8; }}
        code {{ background: #1e293b; color: #38bdf8; padding: 2px 6px; border-radius: 4px; font-family: monospace; }}
        hr {{ border: none; border-top: 1px solid #334155; margin: 2rem 0; }}
        ul {{ line-height: 1.6; }}
    </style>
</head>
<body>
    <pre style="white-space: pre-wrap; font-family: inherit;">{md_content}</pre>
</body>
</html>"""
        return html_doc
